steps:
  # Build sandbox standard image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'SANDBOX_MODE=standard',
           '-t', 'gcr.io/$PROJECT_ID/anthropic-perf-sandbox-standard:latest',
           '-f', 'sandbox/Dockerfile', 'sandbox/']

  # Build sandbox easy image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'SANDBOX_MODE=easy',
           '-t', 'gcr.io/$PROJECT_ID/anthropic-perf-sandbox-easy:latest',
           '-f', 'sandbox/Dockerfile', 'sandbox/']

  # Save sandbox images as tarballs for embedding
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker save gcr.io/$PROJECT_ID/anthropic-perf-sandbox-standard:latest > sandbox_standard.tar
        docker save gcr.io/$PROJECT_ID/anthropic-perf-sandbox-easy:latest > sandbox_easy.tar

  # Build outer harness container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'container/Dockerfile',
           '-t', 'gcr.io/$PROJECT_ID/anthropic-perf-takehome:latest', '.']

images:
  - 'gcr.io/$PROJECT_ID/anthropic-perf-takehome:latest'
  - 'gcr.io/$PROJECT_ID/anthropic-perf-sandbox-standard:latest'
  - 'gcr.io/$PROJECT_ID/anthropic-perf-sandbox-easy:latest'

timeout: '1800s'
